
TESTVALUE1 =  "HELLO"
TESTVALUE2 =  "WORLD"
FULLVALUE = 0
TESTNUM1 = 0
TESTNUM2 = 0
TOTALVALUE = 0

if __name__ == "__main__":
    TESTNUM1 = 8
    TESTNUM2 = 134
    TOTALVALUE =  TESTNUM1 + TESTNUM2
    print(TOTALVALUE)
    print(TESTVALUE1)
    print(TESTVALUE2)
    FULLVALUE=TESTVALUE1+" "+TESTVALUE2
    print(FULLVALUE)
    